### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by wisnukurniawan** [multidots/android-fingerprint-authentication#1]
i get error in 
mFingerPrintAuthHelper = FingerPrintAuthHelper.getHelper(this, this);

**Comment by kevalpatel2106** [comment]
Can you provide details of which android version you are using?

**Comment by wisnukurniawan** [comment]
Im using jellybean API 18
this is my OnCreate code
`@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        buttonGoToSetting = (Button) findViewById(R.id.go_to_settings_btn);
        buttonGoToSetting.setOnClickListener(this);

        mSwitcher = (ViewSwitcher) findViewById(R.id.main_switcher);
        textViewAuthMessage = (TextView) findViewById(R.id.auth_message_tv);

        editTextPin = (EditText) findViewById(R.id.pin_et);
        editTextPin.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence charSequence, int i, int i1, int i2) {

            }

            @Override
            public void onTextChanged(CharSequence charSequence, int i, int i1, int i2) {
                if (charSequence.toString().equals("1234")){
                    Toast.makeText(MainActivity.this, "Success", Toast.LENGTH_SHORT).show();
                    startActivity(new Intent(MainActivity.this, ActivitySuccess.class));
                }
            }

            @Override
            public void afterTextChanged(Editable editable) {

            }
        });

//error: java.lang.NoClassDefFoundError: com.multidots.fingerprintauth.FingerPrintAuthHelper
        mFingerPrintAuthHelper = FingerPrintAuthHelper.getHelper(this, this);
    }`

**Comment by wisnukurniawan** [comment]
In my gradle i set min to 18 and im using Emulator that my device Lollipop. I try in android emulator marshmallow and it works

**Comment by kevalpatel2106** [comment]
Thanks, @wisnukurniawan . Let me check on the devices below Marshmallow. I will get back on this to you.

**Comment by kevalpatel2106** [comment]
@wisnukurniawan This issue is fixed in [v1.0.1](https://github.com/multidots/android-fingerprint-authentication/releases/tag/1.0.1).

**Comment by wisnukurniawan** [comment]
[SOLVED]
now its work
youre so cool!

but my device is not supported haha
