### ISSUE TITLE
onNoFingerPrintHardwareFound

### ISSUE THREAD

**Issue by Ali1067** [multidots/android-fingerprint-authentication#17]
Samsung S5 have Fingerprint scanner. i've registered my finger prints too. but this library is replying no finger print hardware found. 
Solution please

**Comment by kevalpatel2106** [comment]
@Ali1067 Samsung S5 and Note 4 is not supported by android fingerprint APIs. May be [this](https://stackoverflow.com/questions/45499713/which-samsung-devices-do-not-support-androids-native-fingerprint-api) can help you.
