### ISSUE TITLE
Finger Print scanner 

### ISSUE THREAD

**Issue by chanchal12** [multidots/android-fingerprint-authentication#8]
Hi I am having below marshmallow , but it is having finger print scanner how we use this because it gives error that i don't have finger print scanner. please help

**Comment by kevalpatel2106** [comment]
@chanchal12 
Fingerprint scanning support was added in Android 6.0. So android version older than 6.0, won't support fingerprint authentication.

See the behavior changes for Android M: https://developer.android.com/about/versions/marshmallow/android-6.0.html#fingerprint-authentication
